### ISSUE TITLE
Confusing Usage

### ISSUE THREAD

**Issue by sooluh** [acidiney/bull-queue#1]
I'm trying it out, but it's not working. Am I missing any steps?

- [x] Installation done
- [x] Executed `nace configure ...`
- [x] `adonisrc.ts` already contains `@acidiney/bull-queue/queue_provider` in providers
- [x] Created new jobs with `nace make:job ...`
- [x] Registered in `start/jobs.ts`

I want to run the job when opening one of the methods in the controller that has been registered to the route. I call it with the following code:

```ts
await bull.dispatch(ExampleHandlerJob.name, { app, payload } as ExampleHandlerPayload)
```

but it's not working at all. The process inside the `handle()` method doesn't work, even in the `failed()` method.

**Comment by acidiney** [comment]
Hey, could you share with me the code inside the controller? And please confirm witch version are you using

**Comment by acidiney** [comment]
And have you started the worker process? `node ace queue:listen`?

**Comment by sooluh** [comment]
Actually, I haven't executed it yet, but I want when the server is running to simultaneously run BullMQ as well. I create `start/bull.ts` and add it to the preloads in `adonisrc.ts`, and the code is as follows,

```ts
import net from 'net'
import app from '@adonisjs/core/services/app'
import queue from '@acidiney/bull-queue/services/main'

const PORT = 9999
const server = net.createServer()

server.once('error', async (error: any) => {
  if (error.code === 'EADDRINUSE') {
    queue.list().forEach(async (queue) => {
      await queue.close()
    })
  }
})

server.once('listening', async () => {
  server.close()
  // await queue.processBulk(Object.keys(queue.list()))

  if (app.inDev) {
    await queue.ui(PORT || 9999, Object.keys(queue.list()))
  }
})

server.listen(PORT)
```

Any idea? Perhaps my above code is not quite right.
