### ISSUE TITLE
Prevent Redis Connection during Migrations, Seeding & Tests

### ISSUE THREAD

**Issue by D40298008** [acidiney/bull-queue#2]
Hello!

How can I prevent this library from trying to connect to redis during the following scenarios where it isn't needed?

- migrations `node ace migration:run`
- seeding `node ace db:seed`
- unit tests `node ace test`

I tried disabling it in the provider (except for `web`) but then the `node ace queue:listen` fails.
```ts
// adonisrc.ts
providers: [
    () => import('@adonisjs/core/providers/app_provider'),
    //...
    {
        file        : () => import('@acidiney/bull-queue/queue_provider'),
        environment : ['web'],
    },
],
```

**Comment by acidiney** [comment]
Hey, yeah that is a difficult one, the Adonis doesn't provide a easy way to create environments, that's is why it fails.

All these operations are console environment operation, that's is why the package starts and if you ask it to only run it in web, it fails
