### ISSUE TITLE
JobsList as an example is not working

### ISSUE THREAD

**Issue by RafaelTeodoroDev** [acidiney/bull-queue#3]
your example is not working, I made every process, and I have runned `node ace queue:listen`, and I get and message error that says 'Job handler for RegisterStripeCustomer not found', its important remember, I followed full your example

**Comment by acidiney** [comment]
Hey, could you share with me some code, to see if everything is okay

**Comment by acidiney** [comment]
Hey @RafaelTeodoroDev, I think your problem is when you're registering a job on `#start/jobs`. Could you please check the docs again, I have pushed a PR to fix it
