### ISSUE TITLE
Bull UI Fails to Launch

### ISSUE THREAD

**Issue by Zenkylo** [acidiney/bull-queue#5]
Queue works fine, however the Bull UI fails to launch. 
Let me know what additional information is needed to debug.
Thanks
![image](https://github.com/acidiney/bull-queue/assets/11342698/309a9990-e3b5-4e24-9d0f-be5ee205d8ae)

**Comment by Zenkylo** [comment]
After debugging h3 it appears the route is `/admin`. Perhaps the CLI or docs should mention this.

**Comment by acidiney** [comment]
Actually We have it on the docs, maybe we could add an information when someone tries to access /, or do a redirect
