### ISSUE TITLE
Error: Connection Closed

### ISSUE THREAD

**Issue by maukoese** [acidiney/bull-queue#6]
I keep getting this error when I try to build,

The UI runs okay, and the jobs too.

See attached screenshot:

<img width="1008" alt="Screenshot 2024-03-26 at 12 01 30" src="https://github.com/acidiney/bull-queue/assets/14233942/ab24691f-40cf-4b6e-86e3-6c848370b586">

**Comment by acidiney** [comment]
Hey @maukoese, I'm trying to reproduce it on node 21.7.1, but I can't... Could you please tell me the version you're using and the steps to reproduce

**Comment by maukoese** [comment]
It's basically just this error here https://github.com/taskforcesh/bullmq/issues/1218 but not sure what is causing it.
